### ISSUE TITLE
Webserver don't start

### ISSUE THREAD

**Issue by mguyard** [pschmitt/jcalapi#319]
Hello,

In latest docker build, i've an issue with webserver.
After enabled debug logs, nothing appear in logs about webserver except :
```
2024-06-10 16:48:48 2024-06-10 16:48:48.527 | INFO     | logging:callHandlers:1706 - Starting server on 0.0.0.0:7042 with 2 workers
```

When i look in container if tcp/7042 listen, i see nothing
![CleanShot 2024-06-10 at 16 53 08](https://github.com/pschmitt/jcalapi/assets/5262395/9cfaa382-5fe0-4871-8739-3a17ec19fa3b)
I've add iproute2 package to diag this issue.

Except that, all works. I can see in logs that all events are retrieved but not accessible by webserver.

I don't understand where is the issue :(

And of course, when i request webserver, i don't see something in logs as it's when it's works

**Comment by pschmitt** [comment]
How did you start the container exactly?

**Comment by mguyard** [comment]
Tried new build generate this night following this update: https://github.com/pschmitt/jcalapi/commit/f5f36ae2cf72a7bbdc8195905bffdcba077f8ca4

It's better.
Probably due to this issue : https://github.com/dmontagu/fastapi-utils/pull/310
